### ISSUE TITLE
Cannot add images or logos

### ISSUE THREAD

**Issue by Askitask1** [Codeinwp/amadeus#13]
I recently installed the Amadeus theme and none of the buttons for uploading images seem to work. We updated to the latest version of wordpress and reinstalled the theme. Please help.

**Comment by ineagu** [comment]
@mileamadalin does this happen ?

**Comment by Askitask1** [comment]
Turns out that the site had been hacked. The malicious code put on buy the hacker had disabled the image upload functions. The site host engineer was able to execute a clean WP install and remove the malicious code. Now the theme functions appear to be working properly.

Thanks for checking.

**Comment by mileamadalin** [comment]
@ineagu nope, we do not have this issue. I checked on the demo and everything works well.
