### ISSUE TITLE
Customize the upsells

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/amadeus#32]
- Remove current upsells http://prntscr.com/dbjzc8
- Remove Star this theme on WordPress.org!
- At the top of the customizer add a Theme info section with:
  -> Documentation: http://docs.themeisle.com/article/270-amadeus-documentation
  -> View Demo: https://themeisle.com/demo/?theme=Amadeus
  -> Free VS Pro: http://docs.themeisle.com/article/531-what-is-the-difference-between-amadeus-and-amadeus-pro
  -> Leave a review: https://wordpress.org/support/theme/amadeus/reviews/#new-post/

- At the bottom of the customizer add a View PRO version - Get it like on shop isle
  the link is: https://themeisle.com/themes/amadeus-pro/#pricing-single

**Comment by rodica-andronache** [comment]
@cristian-ungureanu i think you worked on production here. and also there are no pull requests

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , done. Sorry!
