### ISSUE TITLE
Redo upsells like on shop isle and llorix

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/amadeus#50]

**Comment by rodica-andronache** [comment]
@abaicus I just realized that this doc http://docs.themeisle.com/article/531-what-is-the-difference-between-amadeus-and-amadeus-pro might be wrong (just copied from Oblique)
From what I've tested, Amadeus pro doesn't have an extra slider option and Integrate with Jetpack related posts . Can you please check too?

**Comment by abaicus** [comment]
Well I'm sure it's copied. Should I just remove them? :D

**Comment by rodica-andronache** [comment]
yes :D

**Comment by abaicus** [comment]
@rodica-andronache I've removed them. :D
