### ISSUE TITLE
Default logo/title

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/amadeus#55]
By default, the setting is set to use the logo without any default logo. It gives out an empty header. Either add a default logo or we should set the default to site title.

@rodica-andronache

**Comment by HardeepAsrani** [comment]
Which way should we go? Any thoughts? Here's what I'll propose:

There should be two options:

- Logo Only
- Logo & Site Title/Description

But if the theme is fresh installed and then it should have 0 as its default (being Logo Only). But if the site contains has no logo, it should display the Site Title by default (or a default logo).

**Comment by rodica-andronache** [comment]
@HardeepAsrani would you like to do this?
I think the easiest solution would be to add a default logo ( maybe the one from the demo ), it shouldn't affect the old users. Could you please check?

**Comment by HardeepAsrani** [comment]
Sure!

**Comment by HardeepAsrani** [comment]
@rodica-andronache There's no default parameter in WP's logo function, so we will have to add it using conditions. What about just showing the title/description by default, if the user has no logo from the last theme they were using?

**Comment by rodica-andronache** [comment]
@HardeepAsrani  yes, soulds good 👍

**Comment by HardeepAsrani** [comment]
```				<div class="site-branding">
					<?php
					if ( function_exists( 'the_custom_logo' ) && get_theme_mod( 'custom_logo' ) && ( get_theme_mod( 'logo_style', 'hide-title' ) == 'hide-title' ) ) {
						the_custom_logo();
					} // End if().

					elseif ( function_exists( 'the_custom_logo' ) && get_theme_mod( 'custom_logo' ) && ( get_theme_mod( 'logo_style', 'hide-title' ) == 'show-title' ) ) {
						the_custom_logo();

						?>

						<h1 class="site-title"><a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home"><?php bloginfo( 'name' ); ?></a></h1>
						<h2 class="site-description"><?php bloginfo( 'description' ); ?></h2>

						<?php
					} /* Only site title and site description */
					else {
						?>
						<h1 class="site-title"><a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home"><?php bloginfo( 'name' ); ?></a></h1>
						<h2 class="site-description"><?php bloginfo( 'description' ); ?></h2>
						<?php
					}
					?>
				</div><!-- .site-branding -->```

@rodica-andronache  I just added a condition to check if logo URL exists then show logo, else show the title & description. What do you think about this solution? It's the simplest one. :)

**Comment by rodica-andronache** [comment]
@HardeepAsrani it sounds good :) make a PR and test to make sure everything is ok for old and new users 👍
