### ISSUE TITLE
red more issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/amadeus#69]
@rodica-andronache 

"Adding the WordPress read more tag "", does not provide a link on the blogs landing page (default index of posts).
In the screenshot (of the default, index, landing page for a blog) attached, you see the last two lines of a post summary that ends with [...]. This is not a link like I would expect, ---"

The user has right. It looks like the read more tag doesn't work on Amadeus. Please see the images attached: 

This is the tag that I'm talking about:

![screen shot 2018-06-25 at 6 28 13 pm](https://user-images.githubusercontent.com/6906834/41859835-c0e8c72c-78a5-11e8-973f-467a915d87f2.png)

This is how we display it on Amadeus:

![screen shot 2018-06-25 at 6 27 42 pm](https://user-images.githubusercontent.com/6906834/41859880-dbb377be-78a5-11e8-843c-59fe2fb35e06.png)

the text is broken and instead, the read more button the phrase was cut and nothing in place.

This is how the default theme displays the tag:

![screen shot 2018-06-25 at 6 26 55 pm](https://user-images.githubusercontent.com/6906834/41859945-046f57cc-78a6-11e8-8f5d-9f41ed960091.png)

**Comment by PatrykWo** [comment]
I know that repo is closed but it looks like the issue still exists.
