### ISSUE TITLE
H1 and H2 issues

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/amadeus#71]
@stefan-cotitosu We have received a message where the user complains that we use H1 for all titles on the theme, but those should be used only on Home Page. For Blog page ex. should be H2

ticket link: https://wordpress.org/support/topic/very-bad-theme-seo-wise/#post-10762740

**Comment by stefan-cotitosu** [comment]
@mileamadalin Thanks for reporting this.

Fixing it may have a huge impact because I have to update the style for many tags.
Due to the complexity of fixing it, I will leave it as it is for the moment.

Please reply here with +1 if you see more users complaining about it.
