### ISSUE TITLE
Font-Awesome bug

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/amadeus#9]
@rodica-andronache we have a bug with Font-Awesome: on Theme options page in Wordpress  we don't have the function to call Fontawesome and all icons are just like squares. 

Possible resolution:

We should open file functions.php, cut line " wp_enqueue_style( 'amadeus-font-awesome', get_template_directory_uri() . '/fonts/font-awesome.min.css' );" from section "Enqueue scripts and styles" and paste it in section "Customizer styles".

**Comment by rodica-andronache** [comment]
this was fixed here: https://github.com/Codeinwp/amadeus/pull/15
